version: '3.1'

services:
  DB-map:
    image: mysql:8
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE -> silently handles warnings
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=django
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=myAppDB

    volumes: 
      - mysql-data:/var/lib/mysql
    networks: 
      - application-network

  api-server:
    depends_on:
      - DB-map
    build:
      context: .
      dockerfile: Dockerfile
    image: myapplication
    ports: 
        - "8080:8080" ## Change if your port is different
    networks: 
      - application-network
    environment:
      - MYSQL_USER=django
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=myAppDB
      - MYSQL_HOST=DB-map
      - SERVER_PORT=8080 ## Change if your port is different
    command: "./wait-for-it/wait-for-it.sh mysql:3306 -- npm run spinupseed"

networks:
  application-network:
    driver: bridge
volumes: 
  mysql-data:
    driver: local